#Cogig db
spring.application.name=fasotour

spring.datasource.url=jdbc:postgresql://localhost:5432/bfa
spring.datasource.username=smith
spring.datasource.password=0814
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/fasotour
server.port=8080

spring.jpa.open-in-view=false
#connexion reste ouverte longtemps.


server.error.include-message=always
server.error.include-binding-errors=always



jwt.secret=fasoTourSecretKeyTresLongueEtSecurePourJWT2024BurkinaFaso
jwt.expiration=86400000

spring.mail.properties.mail.smtp.auth.mechanisms=PLAIN LOGIN
spring.mail.host= smtp.gmail.com
spring.mail.port=587
spring.mail.username=sawadogosakolo@gmail.com
spring.mail.password=jnhn dgrt fqfj bhbu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.enable=5000